// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPtZEgRFzqwtmNaJZaXoA3DMR9dwsp2_U',
    appId: '1:586643162544:web:e9b4b9616bbeba84988275',
    messagingSenderId: '586643162544',
    projectId: 'rpl-b-295f6',
    authDomain: 'rpl-b-295f6.firebaseapp.com',
    storageBucket: 'rpl-b-295f6.appspot.com',
    measurementId: 'G-G30DRKFJYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtj4lhrhscwTH1vWyaPyxtCIQifX7DzOM',
    appId: '1:586643162544:android:a8f49e17eeef5008988275',
    messagingSenderId: '586643162544',
    projectId: 'rpl-b-295f6',
    storageBucket: 'rpl-b-295f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ey5A2eoiUx21nlc2OHH7FyRRjRlp8ew',
    appId: '1:586643162544:ios:8899f66c4575fbbb988275',
    messagingSenderId: '586643162544',
    projectId: 'rpl-b-295f6',
    storageBucket: 'rpl-b-295f6.appspot.com',
    iosClientId: '586643162544-p7ogne9ffb0bqv9f78a0d851svreerla.apps.googleusercontent.com',
    iosBundleId: 'com.example.rplb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ey5A2eoiUx21nlc2OHH7FyRRjRlp8ew',
    appId: '1:586643162544:ios:66f44373b3753c0f988275',
    messagingSenderId: '586643162544',
    projectId: 'rpl-b-295f6',
    storageBucket: 'rpl-b-295f6.appspot.com',
    iosClientId: '586643162544-k3tb7cf8bqtkeb93kpk2kho640dq089m.apps.googleusercontent.com',
    iosBundleId: 'com.example.rplb.RunnerTests',
  );
}
